version: '3.8'

services:
  database:
    container_name: database
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
    ports:
      - '5435:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app/:/var/www
    depends_on:
      - database    

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports: [ '8080:80', '8081:443' ]
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database    