version: '3.8'

services:
  upskill_symfony_database:
    container_name: upskill_symfony_database
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
    ports:
      - '5435:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  upskill_symfony_php:
    container_name: upskill_symfony_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app/:/var/www
    depends_on:
      - upskill_symfony_database    

  upskill_symfony_nginx:
    container_name: upskill_symfony_nginx
    image: nginx:stable-alpine
    ports: [ '8080:80', '8081:443' ]
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - upskill_symfony_php
      - upskill_symfony_database    